README.md

This commit is the result of #12.
It refactors the code so that every button in its respective category is listed by alphabetical order.
Also includes minor changes to code.

♻️ Made every list go in alphabetical order (#12)

---

README.md

fix: issue #90

---

README.md

Update README.md issue #83

---

LICENSE

+ 📄 License 2024 Update

---

README.md

Fixed TailwindCSS text

---

README.md

| [![Netlify](https://img.shields.io/badge/Netlify-%23000000.svg?logo=netlify&logoColor=#00C7B7)](#) | `[![Netlify](https://img.shields.io/badge/Netlify-%23000000.svg?logo=netlify&logoColor=#00C7B7)](#` |
| [![Neovim](https://img.shields.io/badge/Neovim-57A143?logo=neovim&logoColor=fff)](#) | `[![Neovim](https://img.shields.io/badge/Neovim-57A143?logo=neovim&logoColor=fff)](#` |
Vs
| [![Netlify](https://img.shields.io/badge/Netlify-%23000000.svg?logo=netlify&logoColor=#00C7B7)](#) | `[![Netlify](https://img.shields.io/badge/Netlify-%23000000.svg?logo=netlify&logoColor=#00C7B7)](#)` |
| [![Neovim](https://img.shields.io/badge/Neovim-57A143?logo=neovim&logoColor=fff)](#) | `[![Neovim](https://img.shields.io/badge/Neovim-57A143?logo=neovim&logoColor=fff)](#)` |

Fixed formatting problem in README.md

---

README.md

| Codemagic | CI |
| [![Codemagic](https://img.shields.io/badge/Codemagic-0051FF?logo=Codemagic&logoColor=fff)](#) | `[![Codemagic](https://img.shields.io/badge/Codemagic-0051FF?logo=Codemagic&logoColor=fff)](#)` |

Add Codemagic to CI

---

README.md

| Snapcraft | App Stores |
A badge for Snapcraft.io.
| [![Snapcraft](https://img.shields.io/badge/Snapcraft-e95420?logo=snapcraft&logoColor=fff)](#) | `[![Snapcraft](https://img.shields.io/badge/Snapcraft-e95420?logo=snapcraft&logoColor=fff)](#)` |

Add Snapcraft to App Stores

---

README.md

| Flathub | App Stores |
A badge for Flathub.org
| [![Flathub](https://img.shields.io/badge/Flathub-000000?logo=flathub&logoColor=fff)](#) | `[![Static Badge](https://img.shields.io/badge/Flathub-000000?logo=flathub&logoColor=fff)](#)` |

Add Flathub to App Stores

---

README.md

| [Gitea] | [Social Media] |
| [Bitbucket] | [Social Media] |
| [HBO Max] | [Streaming] |
| [Alacritty] | [Terminal Emulator] |
| [Warp] | [Terminal Emulator] |
| [Wezterm] | [Terminal Emulator] |
| [iTerm2] | [Terminal Emulator] |
add badges to Gitea and Bitbucket in social media section.
add badge to HBO Max in streaming section.
add Terminal Emulator section.
add badges to  Alacritty, Warp, WezTerm and iTerm2 to Terminal Emulator section.
| [![Gitea](https://img.shields.io/badge/Gitea-6eaa5b?logo=gitea&logoColor=fff)](#) | `[![Gitea](https://img.shields.io/badge/Gitea-6eaa5b?logo=gitea&logoColor=fff)](#)` |
| [![Bitbucket](https://img.shields.io/badge/Bitbucket-0052CC?logo=bitbucket&l …

feat: add gitea, bitbucket, max, alacritty, warp, wezterm and iterm2 badges

---

CONTRIBUTING.md
README.md

| FastAPI | Frameworks |
Added fastapi badge. Minor changes fixed
| [![FastAPI](https://img.shields.io/badge/FastAPI-009485.svg?logo=fastapi&logoColor=white)](#) | `[![FastAPI](https://img.shields.io/badge/FastAPI-009485.svg?logo=fastapi&logoColor=white)](#)` |

Add - fastpi badge

---

README.md

| Fastify | Framework|
Adding the fastify framework next to good ol express
| [![Fastify](https://img.shields.io/badge/-Fastify-000000?style=flat&logo=fastify&logoColor=white)](#) | `[![Fastify](https://img.shields.io/badge/-Fastify-000000?style=flat&logo=fastify&logoColor=white)](#)` |

feat(fastify): add fastify badge

---

README.md

| Name       | Category   |
|------------|------------|
| ETL           | Data processing  |
| Numpy     | Data processing  |
| Pandas      | Data processing  |
| Matplotlib| Data visualization |
| Chart.js     | Data visualization |
Added Data processing and Data visualization sections.
Added ETL, Numpy and Pandas badges in Data processing.
Added Matplotlib and Chart.js badges in Data visualization.
| [![ETL](https://custom-icon-badges.demolab.com/badge/ETL-9370DB?logo=etl-logo&logoColor=fff)](#) | `[![ETL](https://custom-icon-badges.demolab.com/badge/ETL-9370DB?logo=etl-logo&logoColor=fff)](#)` |
| [![NumPy](https://custom-icon-badges.demolab.com/badge/NumPy-4DABCF?logo=numpy-icon&logoColor=fff)](#) | …

feat: add Data Processing and Data Visualization sections with relevant tools

---

README.md

Corrected anchor for 'Data Visualization' (current target anchor: https://github.com/inttter/md-badges#%EF%B8%8F-data-visualization) in table of contents

Fixed 'Data Visualization' anchor

---

README.md

| Name       | Category   |
|------------|------------|
| Name       | Category   |
Add ORM section with Prisma ORM
| [![Prisma](https://img.shields.io/badge/Prisma-2D3748?logo=prisma&logoColor=white)](#) | `[![Prisma](https://img.shields.io/badge/Prisma-2D3748?logo=prisma&logoColor=white)](#)` |

✨ feat: add prisma ORM

---

README.md

| Name       | Category   |
|------------|------------|
| Odoo       | Cloud Systems   |
Add Odoo badge. 
| [![Odoo](https://img.shields.io/badge/Odoo-714B67?logo=Odoo&logoColor=fff)](#) | `[![Odoo](https://img.shields.io/badge/Odoo-714B67?logo=Odoo&logoColor=fff)](#)` |

feat: add Odoo badge

---

README.md

| Name       | Category   |
|------------|------------|
| Helix       | Code Editors   |
Add a badge for Helix Editor
| [![Helix](https://img.shields.io/badge/Helix-706bc8?logo=helix&logoColor=fff)](#) | `[![Helix](https://img.shields.io/badge/Helix-706bc8?logo=helix&logoColor=fff)](#)` |

✨ feat: add helix badge

---

README.md

Hello,
I'd like to contribute this badge to the project. The badge represents the GNU operating system, known for its contributions to open-source development and its role in the tech community.
Thank you for considering my contribution!
Best regards,
devtracer
* **Name:** GNU
* **Category:** Operating Systems
| [![GNU](https://img.shields.io/badge/GNU-000000?logo=gnu&logoColor=white)](#)        | `[![GNU](https://img.shields.io/badge/GNU-000000?logo=gnu&logoColor=white)](#)`        |

GNU operating system badge

---

README.md

1. https://pytorch.org/
* **Name:** PyTorch
* **Category:** Framework
2. https://www.tensorflow.org/
* **Name:** TensorFlow
* **Category:** Framework
| [![PyTorch](https://img.shields.io/badge/PyTorch-ee4c2c?logo=pytorch&logoColor=white)](#) | `[![PyTorch](https://img.shields.io/badge/PyTorch-ee4c2c?logo=pytorch&logoColor=white)](#)` |
| [![TensorFlow](https://img.shields.io/badge/TensorFlow-ff8f00?logo=tensorflow&logoColor=white)](#) | `[![TensorFlow](https://img.shields.io/badge/TensorFlow-ff8f00?logo=tensorflow&logoColor=white)](#)` |

feat: add TensorFlow & PyTorch badge

---

README.md

* **Name:** scikit-learn
* **Category:** Data Science
| [![Scikit-learn](https://img.shields.io/badge/-scikit--learn-%23F7931E?logo=scikit-learn&logoColor=white)](#) | `[![Scikit-learn](https://img.shields.io/badge/-scikit--learn-%23F7931E?logo=scikit-learn&logoColor=white)](#)` |

feat: add scikit-learn badge

---

README.md

* **Name:** F-Droid
* **Category:** App Store
| [![F-Droid](https://img.shields.io/badge/F--Droid-%2311AB00.svg?logo=f-droid&logoColor=white)](#) | `[![F-Droid](https://img.shields.io/badge/F--Droid-%2311AB00.svg?logo=f-droid&logoColor=white)](#)` |

Added F-Droid to app store section

---

README.md

* **Name:** Keras
* **Category:** Framework
| [![Keras](https://img.shields.io/badge/Keras-D00000?logo=keras&logoColor=fff)](#) | `[![Keras](https://img.shields.io/badge/Keras-D00000?logo=keras&logoColor=fff)](#)` |

✨ feat: add Keras badge

---

README.md

* **Name:** Kaggle, CUDA, and Cursor
* **Category:** Kaggle: Education, CUDA: Framework, Cursor: Code Editor
| [![Kaggle](https://img.shields.io/badge/Kaggle-20BEFF?logo=kaggle&logoColor=fff)](#) | `[![Kaggle](https://img.shields.io/badge/Kaggle-20BEFF?logo=kaggle&logoColor=fff)](#)` |
| [![CUDA](https://img.shields.io/badge/CUDA-76B900?logo=nvidia&logoColor=fff)](#) | `[![CUDA](https://img.shields.io/badge/CUDA-76B900?logo=nvidia&logoColor=fff)](#)` |
| [![Cursor](https://custom-icon-badges.demolab.com/badge/Cursor-000000?logo=cursor-ai-white)](#) | `[![Cursor](https://custom-icon-badges.demolab.com/badge/Cursor-000000?logo=cursor-ai-white)](#)` |

added Kaggle, Cuda, and Cursor badges

---

README.md

Add LangChain badge
* **Name:** LangChain
* **Category:** Framework
| [![LangChain](https://img.shields.io/badge/LangChain-1c3c3c.svg?logo=langchain&logoColor=white)](#) | `[![LangChain](https://img.shields.io/badge/LangChain-1c3c3c.svg?logo=langchain&logoColor=white)]` |

Add LangChain icon in Framework section

---

README.md

1.
* **Name:** Apollo GraphQL
* **Category:** Framework
2.
* **Name:** GraphQL
* **Category:** Framework
| [![Apollo GraphQL](https://img.shields.io/badge/Apollo%20GraphQL-311C87?logo=apollographql&logoColor=fff)](#) | `[![Apollo GraphQL](https://img.shields.io/badge/Apollo%20GraphQL-311C87?logo=apollographql&logoColor=fff)](#)` |
| [![GraphQL](https://img.shields.io/badge/GraphQL-E10098?logo=graphql&logoColor=fff)](#) | `[![GraphQL](https://img.shields.io/badge/GraphQL-E10098?logo=graphql&logoColor=fff)](#)` |

feat: add Apollo GraphQL and GraphQL badge

---

README.md

* **Name:** Postman
* **Category:** API Development [ **NEW** ]
| [![Postman](https://img.shields.io/badge/Postman-FF6C37?logo=postman&logoColor=white)](#) | `[![Postman](https://img.shields.io/badge/Postman-FF6C37?logo=postman&logoColor=white)](#)` |

✨ feat: add Postman badge

---

README.md

* **Name:** Ghostty
* **Category:** Terminal
| [![Ghostty](https://custom-icon-badges.demolab.com/badge/Ghostty-0000ff?logo=ghostty_term)](#) | `[![Ghostty](https://custom-icon-badges.demolab.com/badge/Ghostty-0000ff?logo=ghostty_term)](#)` |

feat: add Ghostty badge

---

README.md

Makes this repository's list more comprehensive! All of these projects are either super-relevant to many people's software projects (so super relevant to include as a resource) or very popular services still missing nonetheless.
I took most of these from either my own projects or profile badges but thought they could maybe be useful here too? :)
P.S: If you need me to separate these into separate PRs, I can do that too
| [![Bruno](https://img.shields.io/badge/Bruno-F4AA41?logo=Bruno&logoColor=black)](#) | `[![Bruno](https://img.shields.io/badge/Bruno-F4AA41?logo=Bruno&logoColor=black)](#)` |
| [![Chrome Web Store](https://img.shields.io/badge/Chrome_Web_Store-4285F4?logo=chromewebstore&logoColor=white)](#) | `[![Chrome Web …

Add Beeper, Chrome Web Store, RubyGems, Firefox Add-Ons, Socket, Thunderbird, Bruno, and Wakatime

---

README.md

I found the following quite useful for me. Let me know if you think they are also useful for your amazing collection!
| [![MLflow](https://img.shields.io/badge/MLflow-0194E2?logo=MLflow&logoColor=black)](#) | `[![MLflow](https://img.shields.io/badge/MLflow-F4AA41?logo=MLflow&logoColor=black)](#)` |
| [![Roboflow](https://img.shields.io/badge/Roboflow-6706CE?logo=Roboflow&logoColor=black)](#) | `[![Roboflow](https://img.shields.io/badge/Roboflow-6706CE?logo=Roboflow&logoColor=black)](#)` |
| [![Google Scholar](https://img.shields.io/badge/Google%20Scholar-4285F4?logo=Google%20Scholar&logoColor=white)](#) | `[![Google Scholar](https://img.shields.io/badge/Google%20Scholar-4285F4?logo=Google%20Scholar&logoColor=white)](#)` |
| …

✨ feat: Add 8 badges
